using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using System.Linq;
using Unity.VisualScripting;


public class PenPaint : MonoBehaviour
{
    public GameObject prefab;
    private List<GameObject> _strokes = new List<GameObject>();

    private void Update()
    {
        Paint();
    }

    private void Paint()
    // a function meant to generate gameobjects as "paint" //
    {
        bool pressed = Pen.current.tip.wasPressedThisFrame;
        if (pressed == true)
        {
            Instantiate(prefab);
            Debug.Log("An instantiation has occured???");
        }
        else
        {
            return;
        }
        
        

    }

    private void Undo()
    // a function meant to destroy the last instance of a gameobject generated by paint //
    {
        GameObject lastItem = _strokes.Last();
        Destroy(lastItem);
        _strokes.Remove(lastItem);
        
        // need to tie undo to an action //
    }

   

}




